import Head from "next/head";

export default function Home() {
  return (
    <div data-theme="cmyk" className="h-screen flex flex-col items-center ">
      <Head>
        <title>Francisco Sepulveda DEV - 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-11/12 flex justify-center">
        <h1 className="text-3xl text-primary">Portfolio con Tailwind</h1>
      </main>
    </div>
  );
}
