import Head from "next/head";
import Hero from "../components/Hero";
import Proyects from "../components/Proyects";

export default function Home() {
  return (
    <div data-theme="cmyk" className="h-full flex flex-col items-center ">
      <Head>
        <title>Francisco Sepulveda DEV - 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-11/12 flex justify-center flex-col items-center pt-[70px] h-full">
        <Hero />
        <Proyects />
      </main>
    </div>
  );
}
